
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: teacher
  datasource:
    url: jdbc:h2:file:D:/others/Learing/h2/teacher/teacher_service;DB_CLOSE_DELAY=-1;
    username: lang
    password: lang123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update