server:
  port: 8082
spring:
  application:
    name: teacher
  profiles:
    active: uat
  config:
    import: optional:configserver:http://configserver:8088/
#  cloud:
#    config:
#      fail-fast: true  # Fail startup if cannot connect to config server
#      retry:
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
#        max-attempts: 20
